# Setup
title:               Pradyumna
tagline:             ''
description:         ''
url:                 'https://www.pradyumna.dev'
baseurl:
paginate:            5

# About/contact
author:
  name:              Pradyumna Shembekar
  url:               https://twitter.com/pradyumna2905
  email:             pradyumna@hey.com

permalink: date
